### ISSUE TITLE
Collect information about new API

### ISSUE THREAD

**Issue by apple502j** [apple502j/scratchapi2#2]
Please do!

# How can I do it?
See README

If you find, please post here. I'll check and open an issue.

**Comment by apple502j** [comment]
#4 An API to get JSON file

**Comment by joker314** [comment]
Why not use the default issue tracker and make a note in the README to file an issue if a new API is found? This way, closed issues aren't deleted here -- making things more cluttered.

**Comment by joker314** [comment]
Note: you closed and reopened
