### ISSUE TITLE
A new reviewer

### ISSUE THREAD

**Issue by apple502j** [apple502j/scratchapi2#3]
When sharing to PyPI, I will need some reviewers. Help me!

**Comment by apple502j** [comment]
@Kenny2github Thanks!

**Comment by wxllow** [comment]
I can help contribute to scratchapi2, I know how to use the Python requests module, just tell me some stuff u want me to add and ill make it as a pull request!

**Comment by micahlt** [comment]
Hey, I’ve been looking in to restarting this project.  Would you be interested @ItzMeWilliam ?

**Comment by wxllow** [comment]
@micahlt Yeah

**Comment by wxllow** [comment]
@micahlt I will give you access to [ItzMeWilliam/BetterScratchAPI](https://github.com/ItzMeWilliam/BetterScratchAPI)
